petQuest/config/routes.rb
Rails.application.routes.draw do

  resources :posts
  
  resources :foods do
    collection {post :import }
  end

  resources :nutritions do
    collection {post :import }
  end

     resources :idealdogweights do
    collection {post :import }
  end
  resources :idealcatweights do
    collection {post :import }
  end

  resources :recipes, except: :add
   

  get 'recipes/:id/add(.:format)' => 'foods#add', :as => :add

  get 'recipes/:id/add_weight(.:format)' => 'recipes#add_weight', :as => :add_weight
  
  get 'about' => 'welcome#about'

  get 'welcome/index'
  get 'welcome/contact'
  get 'welcome/faqs'
  get 'welcome/pricing'
  get 'welcome/features'
  get 'welcome/login'

  get 'getdata' => 'pets#getdata'
  get 'search(.:format)' => 'foods#search', :as => :search
  post 'search(.:format)' => 'foods#search', :as => :searchmore
   resources :pets
   get 'calculate' => 'foods#calculate', :as => :calculate# to calculate the ME for pet(:id)
   post 'calculate' => 'foods#calculate', :as => :calculatemore# to calculate the ME for pet(:id)
    get 'create_multiple' => 'recipes#create_multiple', :as => :createmultiple#
    post 'create_multiple' => 'recipes#create_multiple', :as => :createmultiplemore#
    get 'food/admin' =>'foods#upload'
    get 'food/admin' =>'foods#upload'

   root 'welcome#index'

   get 'getfooddata' => 'foods#getfooddata'

    

end

petQuest/app/models/food.rb
class Food < ActiveRecord::Base
	has_one :nutrition, :dependent => :destroy
	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Food.create! row.to_hash
		end
	end

	
end

petQuest/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.paginate(:page => params[:page], :per_page =>10)
@food = Food.new
    @recipes = Recipe.all
  @recipe=Recipe.new
  @pets=Pet.all


  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food_nutrition   = (Nutrition.find_by( food_id: @food.food_id))
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end
 
  def search
 
  @word= params[:q]
  Rails.logger.debug(@word)

  @foodresults=Food.where('name ILIKE ?',"%#{@word}%").paginate(:page=>params[:page])




   end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
  	Food.import(params[:file])
  	redirect_to foods_path, notice: "Foods Added successfully"
	end

  def add
    @food = Food.find(params[:id])
    Recipe.create( :foodname => @food.name )
    redirect_to foods_path, notice: "Add into recipe successfully"
  end


  
  #
  def getfooddata

    # this contains what has been selected in the first select box

    
    # we get the data for selectbox 2
    if params[:Food] == "Meat&Meat Products"
    @food_data = Food.where(food_category: "Meat&Meat Products")
    end

    if params[:Food] == "Poultry&Poultry Products"
    @food_data = Food.where(food_category: "Poultry&Poultry Products")
    end

    if params[:Food] == "Milk & Eggs"
    @food_data = Food.where(food_category: "Milk & Eggs")
    end

    if params[:Food] == "Fish_Shelfish&Mollusc"
    @food_data = Food.where(food_category: "Fish_Shelfish&Mollusc")
    end

    if params[:Food] == "Seed_Fat&Oils"
    @food_data = Food.where(food_category: "Seed_Fat&Oils")
    end

    if params[:Food] == "Condiments"
    @food_data = Food.where(food_category: "Condiments")
    end

    if params[:Food] == "Cereal&Cereal Products"
    @food_data = Food.where(food_category: "Cereal&Cereal Products")
    end

    if params[:Food] == "Tubers_Starches&Products"
    @food_data = Food.where(food_category: "Tubers_Starches&Products")
    end

    # we get the data for selectbox 2
    if params[:Food] == "root vegetables"
    @food_data = Food.where(food_category: "root vegetables")
    end

    if params[:Food] == "leguminous vegetables_Legume products"
    @food_data = Food.where(food_category: "leguminous vegetables_Legume products")
    end

    if params[:Food] == "solanaceous_melon&fruit vegetables"
    @food_data = Food.where(food_category: "solanaceous_melon&fruit vegetables")
    end

    if params[:Food] == "leafy_flower vegetables"
    @food_data = Food.where(food_category: "leafy_flower vegetables")
    end

    if params[:Food] == "aquatic_tuber vegetable"
    @food_data = Food.where(food_category: "aquatic_tuber vegetable")
    end

    
  
  
  end

   def calculate

#initialize the totals for nutrients
@Energy=0
@Protein=0
@Fat=0
@CHO=0
@Dietaryfiber=0
@Ash=0
@Cholesterol=0
@Retinol=0
@Vitamin_A=0
@Vitamin_K=0
@Vitamin_D=0
@Vitamin_E=0
@Vitamin_C=0
@Vitamin_B1=0
@Vitamin_B2=0
@Vitamin_B3=0
@Vitamin_B6=0
@Vitamin_B12=0
@Folic_acid=0
@Choline=0
@Biotin=0
@Vitamin_B5=0
@Calcium=0
@Phosphorous=0
@Potassium=0
@Sodium=0
@Chloride=0
@Magnesium=0
@Iron=0
@Zinc=0.00
@Selenium=0
@Copper=0
@Manganese=0
@Iodine=0
@Taurine=0
@Isoleucine=0
@Leucine=0
@Lysine=0
@Methionine_cystine=0
@Methionine=0
@Phenylalanine_tyrosine=0
@Phenylalanine=0
@Threonine=0
@Tryptophan=0
@Valine=0
@Arginine=0
@Histidine=0
@Linoleic_acid=0
@Arachidonic_acid=0
@Totalweight=0

#ingredients proportion values
@Meatproportion=0
@Poultryproportion=0
@Milkeggproportion=0
@Fishshellfishproportion=0
@Seedfatoilproportion=0
@Condimentsproportion=0
@Cerealproportion=0
@Tubersproportion=0
@Rootvegetablesproportion=0
@Leguminousvegetablesproportion=0
@Solanaceousvegetablesproportion=0
@Leafyflowervegetablesproportion=0
@Aquaticproportion=0
@Fungiproportion=0






Recipe.all.each do |recipe|

@Food=Nutrition.find_by(foodname:recipe.foodname)


#Add up ingredient proportions
Rails.logger.debug(@Food)
case @Food.category

when 'Meat&Meat Products'
unless recipe.weight.nil? or recipe.weight.nil?
@Meatproportion=recipe.weight+@Meatproportion
end
when 'Poultry&Poultry Products'
unless recipe.weight.nil? or recipe.weight.nil?
@Poultryproportion=recipe.weight+@Poultryproportion
end
when 'Milk & Eggs'
unless recipe.weight.nil? or recipe.weight.nil?
@Milkeggproportion=recipe.weight+@Milkeggproportion
end
when 'Fish_Shelfish&Mollusc'
unless recipe.weight.nil? or recipe.weight.nil?
@Fishshellfishproportion=recipe.weight+@Fishshellfishproportion
end
when 'Seed_Fat&Oils'
unless recipe.weight.nil? or recipe.weight.nil?
@Seedfatoilproportion=recipe.weight+@Seedfatoilproportion
end
when 'Condiments'
unless recipe.weight.nil? or recipe.weight.nil?
@Condimentsproportion=recipe.weight+@Condimentsproportion
end
when 'Cereal And Cereal Products'
unless recipe.weight.nil? or recipe.weight.nil?
@Cerealproportion=recipe.weight+@Cerealproportion
end
when 'Tubers_Starches&Products'
unless recipe.weight.nil? or recipe.weight.nil?
@Tubersproportion=recipe.weight+@Tubersproportion
end
when 'root vegetables'
unless recipe.weight.nil? or recipe.weight.nil?
@Rootvegetablesproportion=recipe.weight+@Rootvegetablesproportion
end
when 'leguminous vegetables_Legume products'
unless recipe.weight.nil?
@Leguminousvegetablesproportion=recipe.weight+@Leguminousvegetablesproportion
end
when 'solanaceous_melon&fruit vegetables'
unless recipe.weight.nil?
@Solanaceousvegetablesproportion=recipe.weight+@Solanaceousvegetablesproportion
end
when 'leafy_flower vegetables'
unless recipe.weight.nil? or recipe.weight.nil?
@Leafyflowervegetablesproportion=recipe.weight+@Leafyflowervegetablesproportion
end
when 'aquatic_tuber vegetable'
unless recipe.weight.nil? or recipe.weight.nil?
@Aquaticproportion=recipe.weight+@Aquaticproportion
end
when 'Fungi&Algae'
unless recipe.weight.nil? or recipe.weight.nil?
@Fungiproportion=recipe.weight+@Fungiproportion
end
end




#adding up individual nutrients
unless @Food.vitaminA.nil? or recipe.weight.nil?
@Vitamin_A=@Vitamin_A+(@Food.vitaminA*recipe.weight)
end
=begin
@Vitamin_D=@Vitamin_D+(@Food.vitaminD*recipe.weight)
=end
unless @Food.zinc.nil? or recipe.weight.nil?
@Zinc=@Zinc+(@Food.zinc*recipe.weight)
end

unless @Food.energy.nil? or recipe.weight.nil?
@Energy=@Energy+(@Food.energy*recipe.weight)
end

unless @Food.protein.nil? or recipe.weight.nil?
@Protein=@Protein+(@Food.protein*recipe.weight)
end

unless @Food.fat.nil? or recipe.weight.nil?
@Fat=@Fat+(@Food.fat*recipe.weight)
end

unless @Food.cho.nil? or recipe.weight.nil?
@CHO=@CHO+(@Food.cho*recipe.weight)
end


unless @Food.dietaryfiber.nil? or recipe.weight.nil?
@Dietaryfiber=@Dietaryfiber+(@Food.dietaryfiber*recipe.weight)
end

unless @Food.ash.nil? or recipe.weight.nil?
@Ash=@Ash+@Food.ash+(@Food.ash*recipe.weight)
end
unless @Food.vitaminE.nil? or recipe.weight.nil?
  @Vitamin_E=@Vitamin_E+(@Food.vitaminE*recipe.weight)
end
  unless @Food.vitaminB1.nil? or recipe.weight.nil?

@Vitamin_B1=@Vitamin_B1+(@Food.vitaminB1*recipe.weight)
end
unless @Food.calcium.nil? or recipe.weight.nil?

@Calcium=@Calcium+(@Food.calcium*recipe.weight)
end
unless @Food.phosphorous.nil? or recipe.weight.nil?

@Phosphorous=@Phosphorous+(@Food.phosphorous*recipe.weight)
end
unless @Food.potassium.nil? or recipe.weight.nil?

@Potassium=@Potassium+(@Food.potassium*recipe.weight)
end
unless @Food.sodium.nil? or recipe.weight.nil?

@Sodium=@Sodium+(@Food.sodium*recipe.weight)
end
unless @Food.magnesium.nil? or recipe.weight.nil?

@Magnesium=@Magnesium+(@Food.magnesium*recipe.weight)
end
=begin

@Cholesterol=@Cholesterol+(@Food.cholesterol*recipe.weight)
@Retinol=@Retinol+(@Food.retinol*recipe.weight)
@Vitamin_K=@Vitamin_K+(@Food.vitaminK*recipe.weight)
@Vitamin_D=@Vitamin_D+(@Food.vitaminD*recipe.weight)
@Vitamin_C=@Vitamin_C+(@Food.vitaminC*recipe.weight)
@Vitamin_B2=@Vitamin_B2+(@Food.vitaminB2*recipe.weight)
@Vitamin_B3=@Vitamin_B3+(@Food.vitaminB3*recipe.weight)
@Vitamin_B6=@Vitamin_B6+(@Food.vitaminB6*recipe.weight)
@Vitamin_B12=@Vitamin_B12+(@Food.vitaminB12*recipe.weight)
@Folic_acid=@Folic_acid+(@Food.folicacid*recipe.weight)
@Choline=@Choline+(@Food.choline*recipe.weight)
@Biotin=@Biotin+(@Food.biotin*recipe.weight)
@Vitamin_B5=@Vitamin_B5+(@Food.vitaminb5*recipe.weigh)
@Chloride=@Chloride+(@Food.chloride*recipe.weight)
@Iron=@Iron+@Food.iron+(@Food.iron*recipe.weight)
@Zinc=@Zinc+@Food.zinc+(@Food.zinc*recipe.weight)
@Selenium=@Selenium+(@Food.selenium*recipe.weight)
@Copper=@Copper+(@Food.copper*recipe.weight)
@Manganese=@Manganese+(@Food.manganese*recipe.weight)
@Iodine=@Iodine+(@Food.iodine*recipe.weight)
@Taurine=@Taurine+(@Food.taurine*recipe.weight)
@Isoleucine=@Isoleucine+(@Food.isoleucine*recipe.weight)
@Leucine=@Leucine+(@Food.leucine*recipe.weight)
@Lysine=@Lysine+(@Food.lysine*recipe.weight)

petQuest/app/helpers/foods_helper.rb
module FoodsHelper
end

petQuest/app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="table-responsive ">
  <table class="table table-bordered">
    <tbody>
      <tr>
        <td><%= f.label :name %></td>
        <td><%= f.text_field :name %></td>
      </tr>  

      <tr>
        <td><%= f.label :description %></td>
        <td><%= f.text_area :description %></td>
      </tr>
      <tr>
        <td><%= f.label :reference_price %></td>
        <td><%= f.text_field :reference_price %></td>
      </tr>
  
      <tr>
        <td><%= f.label :cook_method %></td>
        <td><%= f.text_field :cook_method %></td>
      </tr>

      <tr>
                                      <td><%= f.label :food_category %></td>
                                      <td><div class="controls">
                            <%= f.select(:food_category, options_for_select([
                              ['Meat And Meat Products','Meat And Meat Products'],
                              ['Poultry And Poultry Products','Poultry And Poultry Products'],
                              ['Milk And Eggs','Milk And Eggs'],
                              ['Fish Shelfish And Mollusc','Fish Shelfish And Mollusc'],
                              ['Seed Fat And Oils','Seed Fat And Oils'],
                              ['Condiments','Condiments'],
                              ['Cereal And Cereal Products','Cereal And Cereal Products'],
                              ['Tubers Starches And Products','Tubers Starches And Products'],
                              ['Root Vegetables','Root Vegetables'],
                              ['Leguminous Vegetables And Legume Products','Leguminous Vegetables And Legume Products'],
                              ['Solanaceous Melon And Fruit Vegetables','Solanaceous Melon And Fruit Vegetables'],
                              ['Leafy Flower Vegetables','Leafy Flower Vegetables'],
                              ['Aquatic And Tuber Vegetable','Aquatic And Tuber Vegetable'],
                              ['Fungi And Algae','Fungi And Algae']]), { include_blank: true }) %></div></td>
                                    </tr>
                                    <tr>
                                      <td><%= f.label :img_dir %></td>
                                      <td><%= f.text_field :img_dir %></td>
                                    </tr>
      
  <tr>
    <td><%= f.label :img_dir %></td>
    <td><%= f.text_field :img_dir %></td>
   </tr> 

  <tr>
    <td><%= f.label :food_id %></td>
    <td><%= f.number_field :food_id %></td>
  </tbody></table></div>
<br>
  <div class="actions col-md-offset-5">
    <%= f.submit nil, :class=>"btn btn-danger", :type=>"button"%><% end %>
    <a href="http://localhost:3000/foods" class="btn btn-danger" type="button">Back</a>
  </div>


</div>

petQuest/app/views/foods/_search.html.erb
	<%= form_tag :controller => 'foods', :action => 'search', :method => 'get' do %>
      <%= text_field_tag :search, params[:search], :id => 'search_field' %>
      <%= submit_tag "Search", :name => nil, :class="btn btn-danger" %> 
      <%= link_to_function "Clear", "$('search_field').clear()" %>
  <% end %> 

petQuest/app/views/foods/edit.html.erb
<%=render partial: "layouts/head"%>
<!-- Banner Start -->
			
			<div class="banner padd">
				<div class="container">
					<!-- Image -->
					<img class="img-responsive" src="http://dakotapethospital.com/clients/14546/images/slideshows/29628/banner%204%20edited.jpg" alt="" />
					<!-- Heading -->
					<h2 class="brown">Edit Food</h2>
					<ol class="breadcrumb">
						<li><a href="index.html"></a></li>
						<li class="active"></li>
					</ol>
					<div class="clearfix"></div>
				</div>
			</div>
			
			<!-- Banner End -->
<!-- Booking Start -->
				
				<div class="booking">
					<div class="container">
						<div class="row">
							<div class="col-md-7">
								<!-- Heading -->
								<h3>Edit Food</h3>
								<!-- Paragraph -->
							
								<!-- Image Slider -->
								<img class="img-responsive" src="http://freedwallpaper.com/wp-content/uploads/2014/11/cat-wallpapers-for-desktop-2-1366x768-770958.jpg">
                </div>
						
										
							<div class="col-md-5">
								<!-- Booking form area -->
								<div class="booking-form">
									<!-- Heading -->
									<h3>Edit food</h3>
									<!-- Paragraph -->
								
									<!-- Booking form -->
									<%= form_for(@food) do |f| %>
										  <% if @food.errors.any? %>
										    <div id="error_explanation">
										      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

										      <ul>
										      <% @food.errors.full_messages.each do |message| %>
										        <li><%= message %></li>
										      <% end %>
										      </ul>
										    </div>
										  <% end %>

										  <div class="table-responsive ">
						                    <table class="table table-bordered">
						                      
						                      <tbody>
						                        <tr>
						                          <td><%= f.label :name %></td>
						                          <td> <%= f.text_field :name %></td>
						                        </tr>
						                        <tr>
						                          <td><%= f.label :description %></td>
						                          <td><%= f.text_area :description %></td>
						                        </tr>
						                        <tr>
						                          <td><%= f.label :reference_price %></td>
						                          <td><%= f.text_field :reference_price %></td>
						                        </tr>
						                        <tr>
						                        	<td><%= f.label :cook_method %></td>
						                        	<td><%= f.text_field :cook_method %></td>
						                        </tr>	
						                        <tr>
						                        	<td><%= f.label :food_category %></td>
						                        	<td><div class="controls">
										        <%= f.select(:food_category, options_for_select([
										          ['Meat And Meat Products','Meat And Meat Products'],
										          ['Poultry And Poultry Products','Poultry And Poultry Products'],
										          ['Milk And Eggs','Milk And Eggs'],
										          ['Fish Shelfish And Mollusc','Fish Shelfish And Mollusc'],
										          ['Seed Fat And Oils','Seed Fat And Oils'],
										          ['Condiments','Condiments'],
										          ['Cereal And Cereal Products','Cereal And Cereal Products'],
										          ['Tubers Starches And Products','Tubers Starches And Products'],
										          ['Root Vegetables','Root Vegetables'],
										          ['Leguminous Vegetables And Legume Products','Leguminous Vegetables And Legume Products'],
										          ['Solanaceous Melon And Fruit Vegetables','Solanaceous Melon And Fruit Vegetables'],
										          ['Leafy Flower Vegetables','Leafy Flower Vegetables'],
										          ['Aquatic And Tuber Vegetable','Aquatic And Tuber Vegetable'],
										          ['Fungi And Algae','Fungi And Algae']]), { include_blank: true }) %></div></td>
						                        </tr>
						                        <tr>
						                        	<td><%= f.label :img_dir %></td>
						                        	<td><%= f.text_field :img_dir %></td>
						                        </tr>
						                        <tr>
						                        	<td><%= f.label :food_id %><br></td>
						                        	<td><%= f.number_field :food_id %></td>
						                        </tr></tbody>
						                        </table></div>
										
										 										  
  <div class="actions col-md-offset-4">
    
    <%= f.submit nil, :class=>"btn btn-danger", :type=>"button"%><% end %>
    <a href="http://localhost:3000/foods" class="btn btn-danger" type="button">Back</a>
  </div>


</div>

									
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<!-- Booking End -->      
<!-- Footer Start -->
<%=render partial:"layouts/foot"%>    	
			
			
<!-- Footer End -->

petQuest/app/views/foods/getfooddata.html.erb
<%=render partial: "layouts/head"%>

<!-- Banner Start -->
      
      <div class="banner padd">
        <div class="container">
          <!-- Image -->
          <img class="img-responsive" src="http://dakotapethospital.com/clients/14546/images/slideshows/29628/banner%204%20edited.jpg" alt="" />
          <!-- Heading -->
          <h2 class="brown">View Search Result</h2>
          <ol class="breadcrumb">
            <li><a href="index.html"></a></li>
            <li class="active"></li>
          </ol>
          <div class="clearfix"></div>
        </div>
      </div>
      
      <!-- Banner End -->
<div class = "container"> 
 <div class = "row">    
  <div class="col-md-10 col-md-offset-1">
      <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr id="tr1">
                <th>Name</th>
                
                
                
                <th>Food category</th>
                
                <th>Food id</th>
                <th colspan="4"></th>
              </tr>
            </thead>

            <tbody>
              <% @food_data.each do |food| %>
                <tr>
                  <td><%= food.name %></td>
                 
                  <td><%= food.food_category %></td>
               
                  <td><%= food.food_id %></td>
                  <td><%= link_to 'Show', food %></td>
                  <td><%= link_to 'Add to recipe',  add_path(food) %></td>
                  
                </tr>
              <% end %>
            </tbody>
          </table>
    <br />


     <div align="center"><a href="http://localhost:3000/foods" class="btn btn-danger">Back</a></div>


</div></div></div></div>
<br><br>
<%= render partial: "layouts/foot"%>

     <a href="http://localhost:3000/welcome/index" class="btn2">Back to homepage</a></div>

</div>

petQuest/app/views/foods/new.html.erb
<%=render partial: "layouts/head"%>
<!-- Banner Start -->
      
      <div class="banner padd">
        <div class="container">
          <!-- Image -->
          <img class="img-responsive" src="http://dakotapethospital.com/clients/14546/images/slideshows/29628/banner%204%20edited.jpg">
          <!-- Heading -->
          <h2 class="brown">New Food</h2>
          <ol class="breadcrumb">
            <li><a href="index.html"></a></li>
            <li class="active"></li>
          </ol>
          <div class="clearfix"></div>
        </div>
      </div>
      
      <!-- Banner End -->
<!-- Booking Start -->
				
				<div class="booking">
					<div class="container">
						<div class="row">
							<div class="col-md-7">
								<!-- Heading -->
								<h3>New Food</h3>
								<!-- Paragraph -->
							
								<!-- Image Slider -->
								<img class="img-responsive" src="http://www.papillonpalsrescue.com/images/a-lot-of-dogs.jpg" alt="" ></div>
										
							<div class="col-md-5">
								<!-- Booking form area -->
								<div class="booking-form">
									<!-- Heading -->
									<h3>Add your pet's food</h3>
									<!-- Paragraph -->
									<!-- Booking form -->
									<%= render "form"%>
									
								</div>
							</div>
						</div>
					</div>
				</div>
				
				<!-- Booking End -->      
<!-- Footer Start -->
			
		<%=render partial:"layouts/foot"%>  
			
			<!-- Footer End -->

petQuest/app/views/foods/search.html.erb
<%=render partial: "layouts/head"%>

<!-- Banner Start -->
      
      <div class="banner padd">
        <div class="container">
          <!-- Image -->
          <img class="img-responsive" src="http://dakotapethospital.com/clients/14546/images/slideshows/29628/banner%204%20edited.jpg" alt="" />
          <!-- Heading -->
          <h2 class="brown">View Search Result</h2>
          <ol class="breadcrumb">
            <li><a href="index.html"></a></li>
            <li class="active"></li>
          </ol>
          <div class="clearfix"></div>
        </div>
      </div>
      
      <!-- Banner End -->
<div class = "container"> 
 <div class = "row">    
  <div class="col-md-10 col-md-offset-1">
      <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr id="tr1">
                <th>Name</th>
                
                <th>Food category</th>
                
                <th>Food id</th>
                <th colspan="4"></th>
              </tr>
            </thead>

            <tbody>
              <% @foodresults.each do |food| %>
                <tr>
                  <td><%= food.name %></td>
                
                  <td><%= food.food_category %></td>
                 
                  <td><%= food.food_id %></td>
                  <td><%= link_to 'Show', food %></td>
                  <td><%= link_to 'Add to recipe',  add_path(food) %></td>
                  
                  
                </tr>
              <% end %>
            </tbody>
          </table>
    <br />
    <%= will_paginate @foodresults %>
    <%= page_entries_info @foodresults, :entry_name => 'food'%> <br />

     <div align = "center"><a href="http://localhost:3000/foods" class="btn btn-danger">Back</a>
     </div></div>


</div></div></div></div>
<br><br>
<%= render partial: "layouts/foot"%>

     </div>

</div>

petQuest/app/views/foods/search_results.html.erb
 <ul>
    <% @foods.each do |food| %>
  <li><%= link_to food.title, 
    :action => 'show', :id =>food.food_id  %></li>
  <% end %>
  </ul>