petQuest/config/routes.rb
Rails.application.routes.draw do

  resources :posts
  
  resources :foods do
    collection {post :import }
  end

  resources :nutritions do
    collection {post :import }
  end

     resources :idealdogweights do
    collection {post :import }
  end
  resources :idealcatweights do
    collection {post :import }
  end

  resources :recipes, except: :add
   

  get 'recipes/:id/add(.:format)' => 'foods#add', :as => :add

  get 'recipes/:id/add_weight(.:format)' => 'recipes#add_weight', :as => :add_weight
  
  get 'about' => 'welcome#about'

  get 'welcome/index'
  get 'welcome/contact'
  get 'welcome/faqs'
  get 'welcome/pricing'
  get 'welcome/features'
  get 'welcome/login'

  get 'getdata' => 'pets#getdata'
  get 'search(.:format)' => 'foods#search', :as => :search
  post 'search(.:format)' => 'foods#search', :as => :searchmore
   resources :pets
   get 'calculate' => 'foods#calculate', :as => :calculate# to calculate the ME for pet(:id)
   post 'calculate' => 'foods#calculate', :as => :calculatemore# to calculate the ME for pet(:id)
    get 'create_multiple' => 'recipes#create_multiple', :as => :createmultiple#
    post 'create_multiple' => 'recipes#create_multiple', :as => :createmultiplemore#
    get 'food/admin' =>'foods#upload'
    get 'food/admin' =>'foods#upload'

   root 'welcome#index'

   get 'getfooddata' => 'foods#getfooddata'

    

end

petQuest/app/views/foods (copy)/index.html.erb
<h1>Food list here:</h1>
<%= link_to 'New food', new_food_path %>
<div class="media">
  <div class= "media-body">
    <table class= "table table-condensed">
      <tr>
        <th>picture</th>
        <th>foodCategory</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
     
      <% @foods.each do |food| %>
        <tr>
          <td> <img src="/assets/u88.jpg" class="img-responsive" alt="Salmon"> </td>
          <td><%= food.foodCategory %></td>
          <td><%= food.name %></td>
          <td><%= link_to 'Details', food_path(food), class: 'btn btn-mini btn-primary' %></td>
          <td><%= link_to 'NutritionFacts', nutritionfacts_path, class: 'btn btn-mini btn-success' %></td>
          <td><%= link_to 'AddToRecipe', recipes_path, class: 'btn btn-mini btn-danger' %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

petQuest/app/views/foods (copy)/new.html.erb
<div class="container">
  <h1>Input New Food Here</h1>
<%= form_for :food, url: foods_path do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :referencePrice %><br>
    <%= f.text_field :referencePrice %>
  </p>
  
  <p>
    <%= f.label :ediblePercentage %><br>
    <%= f.text_field :ediblePercentage %>
  </p>
 
 <div class="control-group">
    <%= f.label :cookMethod %><br>
    <%= f.text_field :cookMethod %>
    <div class="controls">
      <%= f.select(:cookMethod, options_for_select([['bake','bake'],['grill','grill']]), { include_blank: true }) %>
    </div>
</div>

  <p>
    <%= f.label :foodCategory %><br>
    <%= f.text_field :foodCategory %>
    <div class="controls">
      <%= f.select(:foodCategory, options_for_select([
        ['Meat&Meat Products','Meat&Meat Products'],
        ['Poultry&Poultry Products','Poultry&Poultry Products'],
        ['Milk & Eggs','Milk & Eggs'],
        ['Fish_Shelfish&Mollusc','Fish_Shelfish&Mollusc'],
        ['Seed_Fat&Oils','Seed_Fat&Oils'],
        ['Condiments','Condiments'],
        ['Cereal&Cereal Products','Cereal&Cereal Products'],
        ['Tubers_Starches&Products','Tubers_Starches&Products'],
        ['root vegetables','root vegetables'],
        ['leguminous vegetables_Legume products','leguminous vegetables_Legume products'],
        ['solanaceous_melon&fruit vegetables','solanaceous_melon&fruit vegetables'],
        ['leafy_flower vegetables','leafy_flower vegetables'],
        ['aquatic_tuber vegetable','aquatic_tuber vegetable'],
        ['fungi&Algae','fungi&Algae']]), { include_blank: true }) %>
    </div>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', foods_path %>
</div>

petQuest/app/views/foods (copy)/show.html.erb
<p>
  <strong>name:</strong>
  <%= @food.name %>
</p>
 
<p>
  <strong>description:</strong>
  <%= @food.description %>
</p>

<p>
  <strong>referencePrice:</strong>
  <%= @food.referencePrice %>
</p>

<p>
  <strong>ediblePercentage:</strong>
  <%= @food.ediblePercentage %>
</p>

<p>
  <strong>cookMethod:</strong>
  <%= @food.cookMethod %>
</p>

<p>
  <strong>foodCategory:</strong>
  <%= @food.foodCategory %>
</p>

<%= link_to 'Back', foods_path %>