petQuest/config/routes.rb
Rails.application.routes.draw do

  resources :posts
  
  resources :foods do
    collection {post :import }
  end

  resources :nutritions do
    collection {post :import }
  end

     resources :idealdogweights do
    collection {post :import }
  end
  resources :idealcatweights do
    collection {post :import }
  end

  resources :recipes, except: :add
   

  get 'recipes/:id/add(.:format)' => 'foods#add', :as => :add

  get 'recipes/:id/add_weight(.:format)' => 'recipes#add_weight', :as => :add_weight
  
  get 'about' => 'welcome#about'

  get 'welcome/index'
  get 'welcome/contact'
  get 'welcome/faqs'
  get 'welcome/pricing'
  get 'welcome/features'
  get 'welcome/login'

  get 'getdata' => 'pets#getdata'
  get 'search(.:format)' => 'foods#search', :as => :search
  post 'search(.:format)' => 'foods#search', :as => :searchmore
   resources :pets
   get 'calculate' => 'foods#calculate', :as => :calculate# to calculate the ME for pet(:id)
   post 'calculate' => 'foods#calculate', :as => :calculatemore# to calculate the ME for pet(:id)
    get 'create_multiple' => 'recipes#create_multiple', :as => :createmultiple#
    post 'create_multiple' => 'recipes#create_multiple', :as => :createmultiplemore#
    get 'food/admin' =>'foods#upload'
    get 'food/admin' =>'foods#upload'

   root 'welcome#index'

   get 'getfooddata' => 'foods#getfooddata'

    

end

petQuest/app/models/pet.rb
class Pet < ActiveRecord::Base

    validates :name, presence: true, length: { in: 2..15 },
                     uniqueness: true
    validates :gender, presence:true
    validates :body_weight, :numericality=>true, :presence=>true
    validates :pet_type, presence:true
    validates :breed, presence:true
    validates :body_condition_score, presence:true
    validates :age, :numericality=>true, :presence=>true
    
end

petQuest/app/controllers/pets_controller.rb
require 'csv'

class PetsController < ApplicationController
    def index
    require 'csv'  



    @pets = Pet.all
    end
    
	def new
        @pet=Pet.new
	end

  def create
   
  	@pet = Pet.new(pet_params)

  	if @pet.save
        redirect_to @pet
   	else
      	render 'new'
    end
	end

  def edit
  @pet = Pet.find(params[:id])
  end

  def show
        @pet=Pet.find(params[:id])
        # for pet show page, fix X year(s) Y month(s) display 
        if @pet.age.to_f == 1 || 0
           @plural_year = "year"
        else
           @plural_year = "years"
        end
        if @pet.months.to_f == 1 || 0
           @plural_month = "month"
        else
           @plural_month = "months"
        end
        case @pet.pet_type
      when "Cat" 
            if @pet.age.to_f < 1 # it is kitten
              @weight_min = (Idealcatweight.find_by(english_name: @pet.breed).min_kg).to_f || "no such cat found"
              @weight_max = (Idealcatweight.find_by(english_name: @pet.breed).max_kg).to_f || "no such cat found"
              @R_me_min = (100 * (@pet.body_weight.to_f ** 0.67.to_f) * 6.732.to_f * (2.718.to_f ** (-0.189.to_f*@pet.body_weight.to_f/@weight_min)-0.66.to_f)).round(2)
              @R_me_max = (100 * (@pet.body_weight.to_f ** 0.67.to_f) * 6.732.to_f * (2.718.to_f ** (-0.189.to_f*@pet.body_weight.to_f/@weight_max)-0.66.to_f)).round(2)
              @me_result = (0.5.to_f * (@R_me_min + @R_me_max)).round(2)

   
          else # it is adult cat
            case @pet.body_condition_score
            when "Normal" # slim-medium adult cat
              @me_result = (100 * @pet.body_weight ** 0.67).round(2)
            when "Fat"
              @me_result = (130 * @pet.body_weight ** 0.4).round(2)
            end
          end

      when "Dog"
        if @pet.age.to_f < 1 # it is puppy
          @weight_min = (Idealdogweight.find_by(english_name: @pet.breed).min_kg).to_f || "no such dog found"
              @weight_max = (Idealdogweight.find_by(english_name: @pet.breed).max_kg).to_f || "no such dog found"
              @R_me_min = (130 * (@pet.body_weight.to_f ** 0.75.to_f) * 3.2.to_f * (2.718.to_f ** (-0.87.to_f * @pet.body_weight.to_f / @weight_min) - 0.1.to_f)).round(2)
              @R_me_max = (130 * (@pet.body_weight.to_f ** 0.75.to_f) * 3.2.to_f * (2.718.to_f ** (-0.87.to_f * @pet.body_weight.to_f / @weight_max) - 0.1.to_f)).round(2)
              @me_result = (0.5.to_f * (@R_me_min + @R_me_max)).round(2)

        else # it is adult dog
          if @pet.age.to_f > 7 || @pet.activity == "Inactive" # old or inactive dog
            @me_result = (95 * @pet.body_weight ** 0.75.to_f).round(2)
          elsif @pet.body_weight <= 23 # small-medium adult dog
            @me_result = (180 * @pet.body_weight ** 0.75.to_f).round(2)
          else # large adult dog
            @me_result = (200 * @pet.body_weight ** 0.75.to_f).round(2)
          end
        end
      else 
        puts "no such pet type found"
      end
      
    # decimal numbers like 0.67, 6.732 will be considered as string rather than number if input directly
    # thererfore, we use .to_f to convert it into fraction then compute
    # ** = ^
    # .round(2) means round up to nearest integer. If round up to tenth decimal, then it should be .round(1) .rb
  
  end

  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet=Pet.find(params[:id])
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def getdata

    # this contains what has been selected in the first select box

    Rails.logger.debug("Params: #{params[:pet][:pet_type]}")
    Rails.logger.debug('test3')
    # we get the data for selectbox 2
    if params[:pet][:pet_type] == "Dog"
         Rails.logger.debug('test4')
    @data_for_select2 = Idealdogweight.all
    end
    if params[:pet][:pet_type] == "Cat"
    @data_for_select2 = Idealcatweight.all
    end
    Rails.logger.debug("Params: #{@data_for_select2.inspect}")

    
    
    if params[:pet][:pet_type] != ""
   Rails.logger.debug('test5')
    # render an array in JSON containing arrays like:
    #[[:id1, :name1], [:id2, :name2]]
    render :json => @data_for_select2.map{|c| [c.english_name, c.english_name]}
    else

    render :json => [['',''],['','']]
    end
  end

def update
  @pet = Pet.find(params[:id])
 
  if @pet.update(pet_params)
    redirect_to @pet
  else
    render 'edit'
  end
end




private
  def pet_params
  	  
      params.require(:pet).permit(:name, :gender, :age, :months, :pet_type, :body_condition_score, :body_weight, :breed, :activity)
	
  end

     
end

petQuest/app/helpers/pets_helper.rb
module PetsHelper
end

petQuest/app/views/pets/edit.html.erb
<%=render partial: "layouts/head"%>
<!-- Banner Start -->
      
      <div class="banner padd">
        <div class="container">
          <!-- Image -->
          <img class="img-responsive" src="http://dakotapethospital.com/clients/14546/images/slideshows/29628/banner%204%20edited.jpg" alt="" />
          <!-- Heading -->
          <h2 class="brown">Edit Pets</h2>
          <ol class="breadcrumb">
            <li><a href="index.html"></a></li>
            <li class="active"></li>
          </ol>
          <div class="clearfix"></div>
        </div>
      </div>
      
      <!-- Banner End -->
 <!-- Booking Start -->
        
   
          <div class="container">
            <div class="row">
              <div class="col-md-7">
                <!-- Heading -->
                
                <!-- Paragraph -->

                <p><br></p>
                <p><br></p>


                
                <!-- Image Slider -->
                <br>
                <img class="img-responsive" src="http://freedwallpaper.com/wp-content/uploads/2014/11/cat-wallpapers-for-desktop-2-1366x768-770958.jpg">
                </div>
              
              <div class="col-md-5">
                <!-- Booking form area -->
             
                  <!-- Heading -->
                  <h3>Edit pets</h3>
                  <!-- Paragraph -->

                  <!-- Booking form -->

                  <%= form_for :pet, url: pet_path(@pet), method: :patch do |f| %>
 

                    <% if @pet.errors.any? %>
                      <div id="error_explanation">
                        <h2>
                          <%= pluralize(@pet.errors.count, "error") %> prohibited
                          this pet from being saved:
                        </h2>
                        <ul>
                          <% @pet.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="table-responsive ">
                    <table class="table table-bordered">
                      
                      <tbody>

                        <tr>
                          <td><%= f.label :name %></td>
                          <td> <%= f.text_field :name %></td>
                        </tr>
                        <tr>
                          <td><%= f.label "Gender" %></td>
                          <td><%= f.select(:gender,options_for_select([['Male',"Male"],  
                          ['Female',"Female"]])) %></td>
                        </tr>
                        <tr>
                          <td><%= f.label "Age (in years)" %></td>
                          <td> <%= f.text_field :age %></td>
                        </tr>
                        <tr>
                          <td><%= f.label "Age (in months)" %></td>
                          <td><%= f.text_field :months %></td>
                        </tr>
                        <tr>
                          <td><%= f.label "Pet Type" %></td>
                          <td> <%= 
                    f.select :pet_type,options_for_select([["Cat", "Cat"], ['Dog',"Dog"]]),{:include_blank=>true}, :id=>"first_select", 
                        :'data-remote' => 'true', # important for UJS
                        :'data-url' => url_for(:controller => 'pets', :action => 'getdata'), # we get the data from here!
                        :'data-type' => 'json' # tell jQuery to parse the response as JSON!
                  %></td>
                        </tr>
                        <tr>
                          <td><%= f.label :Breed %></td>
                          <td> <%= 
                    f.select :breed,"<option>Please select something from first select!</option>",{},:id=>"second_select"
                  %></td>
                        </tr>
                        <tr>
                          <td><%= f.label :body_condition_score %></td>
                          <td> <%= f.select(:body_condition_score,options_for_select([['Slim/Normal',"Normal"],            ['Fat',"Fat"]])) %></td>
                        </tr>
                         <tr>
                          <td><%= f.label "weight in Kg" %></td>
                          <td> <%= f.text_field :body_weight %></td>
                        </tr>
                         </tr>
                         <tr>
                          <td><%= f.label :activity_level %></td>
                          <td> <%= f.select(:activity,options_for_select([['Active',"Active"],            ['Inactive',"Inactive"]])) %></td>
                        </tr>

<%
=begin %>
<%= form_for :pet, url: pet_path(@pet), method: :patch do |f| %>
 
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pet.errors.count, "error") %> prohibited
        this pet from being saved:
      </h2>
      <ul>
        <% @pet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%end%>
<%
=end %>

                      </tbody>
                    </table>
    <div class="col-md-offset-4"><%= f.submit nil, :class=>"btn btn-danger"%>
      <%= link_to 'Back', @pet, class:"btn btn-danger" %>
    <a href="http://localhost:3000/pets" ></a> <%end%></div></div></div></div> </div>
   
                  
               
             
        
        <!-- Booking End -->  
<%=render partial: "layouts/foot"%>    

petQuest/app/views/pets/index.html.erb
<%=render partial: "layouts/head"%>
<!-- Banner Start -->
      
      <div class="banner padd">
        <div class="container">
          <!-- Image -->
          <img class="img-responsive" src="http://dakotapethospital.com/clients/14546/images/slideshows/29628/banner%204%20edited.jpg" alt="" />
          <!-- Heading -->
          <h2 class="brown">View Pets</h2>
          <ol class="breadcrumb">
            <li><a href="index.html"></a></li>
            <li class="active"></li>
          </ol>
          <div class="clearfix"></div>
        </div>
      </div>
      
      <!-- Banner End -->
 <div class = "container"> 
 <div class = "row">    
  <div class="col-md-10 col-md-offset-1">
    <div class ="table-responsive"><table class="table table-bordered">
    
  <tr>
      <th style ="text-align:center">Name&nbsp</th>
      <th style ="text-align:center">&nbspAge in years&nbsp</th> 
      <th style ="text-align:center">&nbspAge in months &nbsp</th> 
      <th style ="text-align:center">&nbspGender&nbsp</th>
      <th style ="text-align:center">&nbspPet_Type&nbsp</th>
      <th style ="text-align:center">&nbspBreed&nbsp</th>
      <th style ="text-align:center">&nbspBody_Condition_Score&nbsp</th>
      <th style ="text-align:center">&nbspWeight&nbsp</th>
      <th style ="text-align:center">&nbspActivity_Level&nbsp</th>
      <th colspan="3"></th>
    </tr>
   
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %>&nbsp<br></td>
        <td>&nbsp<%= pet.age %>&nbsp</td>
 	<td>&nbsp<%= pet.months %>&nbsp</td>
        <td>&nbsp<%= pet.gender %>&nbsp</td>
        <td>&nbsp<%= pet.pet_type %>&nbsp</td>
        <td>&nbsp<%= pet.breed %>&nbsp</td>
        <td>&nbsp<%= pet.body_condition_score %>&nbsp</td>
        <td>&nbsp<%= pet.body_weight %>&nbsp</td>
        <td>&nbsp<%= pet.activity %>&nbsp</td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>

    <% end %>
  </table></div></div>
<div class="col-md-12" align="center">
<a href="http://localhost:3000/foods" class="btn btn-danger" type="button">Select food for pets</a>
<a href="http://localhost:3000/pets/new" class="btn btn-danger" type="button">Add new pets</a>
<br><br><br></div></div>
</div>

<%=render partial:"layouts/foot"%>

<% 
=begin %>
<h3>Import Cat breeds</h3>
<div align="center"><%= form_tag import_idealcatweights_path, multipart: true do  %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Cat Breeds",:class => 'btn2' %>
<% end %></div>
<h3>Import Dog breeds</h3>
<div align="center"><%= form_tag import_idealdogweights_path, multipart: true do  %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Dog Breeds",:class => 'btn2' %>
<% end %></div>
<% 
=end 
%>

petQuest/app/views/pets/me.html.erb
<%=render partial: "layouts/head"%>
<!-- Banner Start -->
      
      <div class="banner padd">
        <div class="container">
          <!-- Image -->
          <img class="img-responsive" src="http://dakotapethospital.com/clients/14546/images/slideshows/29628/banner%204%20edited.jpg" alt="" />
          <!-- Heading -->
          <h2 class="brown">ME Result</h2>
          <ol class="breadcrumb">
            <li><a href="index.html"></a></li>
            <li class="active"></li>
          </ol>
          <div class="clearfix"></div>
        </div>
      </div>
      <!-- Banner End -->
				<div class="showcase">
					<div class="container">
						<div class="row">
							<div class="col-md-10 col-sm-10 col-md-offset-1">
								<!-- Showcase section item -->
								<div class="showcase-item">
									<!-- Image -->
									<img class="img-responsive" src="http://cdn.pet360.com/pet360/Content/Images/CMS/Cat-Dog.png" alt="" />
									<!-- Heading -->
									<h3><a href="#">ME Result:</a></h3>
									<!-- Paragraph -->
									<p><%= @me_result%></p>
									<div align="center"><%= link_to 'Back', pet_path(@pet), :class=>"btn btn-danger"%></div>
									<br>
									<div class="clearfix"></div>
								</div>
							</div></div></div></div>
							<br><br><br>

<%= render partial: "layouts/foot"%>

petQuest/app/views/pets/new.html.erb
<%=render partial: "layouts/head"%>
<!-- Banner Start -->
      
      <div class="banner padd">
        <div class="container">
          <!-- Image -->
          <div class="col-md-12"><img class="img-responsive" src="http://dakotapethospital.com/clients/14546/images/slideshows/29628/banner%204%20edited.jpg" alt="" /></div>
          <!-- Heading -->
          <h2 class="brown">New Pet</h2>
          <ol class="breadcrumb">
            <li><a href="index.html"></a></li>
            <li class="active"></li>
          </ol>
          <div class="clearfix"></div>
        </div>
      </div>
      
      <!-- Banner End -->
<!-- Booking Start -->
        
        <div class="booking">
          <div class="container">
            <div class="row">

              <div class="col-md-7">
                <!-- Heading -->
                <br> </br>
                <!-- Paragraph -->
              
                <!-- Image Slider -->
                <br>
                <img class="img-responsive" src="http://www.hdwallpapers11.com/wallpapers/2560x1600/cute-white-dog-2560x1600.jpg">
              </div>
              <div class="col-md-5">
                <!-- Booking form area -->
                <div class="booking-form">
                  <!-- Heading -->
                  <h3>Add new pets</h3>
                  <!-- Paragraph -->
                  
                  <!-- Booking form -->
                  <%= form_for :pet, url: pets_path(@pet) do |f| %>

                   <% if @pet.errors.any? %>
                      <div id="error_explanation" align="center">
                        <h2>
                          <%= pluralize(@pet.errors.count, "error") %> prohibited
                          this pet from being saved:
                        </h2>
                        <ul>
                          <% @pet.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="table-responsive ">
                    <table class="table table-bordered">
                      
                      <tbody>
                        <tr>
                          <td><%= f.label :name %></td>
                          <td> <%= f.text_field :name %></td>
                        </tr>
                        <tr>
                          <td><%= f.label "Gender" %></td>
                          <td><%= f.select(:gender,options_for_select([['Male',"Male"],  
                          ['Female',"Female"]])) %></td>
                        </tr>
                        <tr>
                          <td><%= f.label "Age (in years)" %></td>
                          <td> <%= f.text_field :age %></td>
                        </tr>
                        <tr>
                          <td><%= f.label "Age (in months)" %></td>
                          <td><%= f.text_field :months %></td>
                        </tr>
                        <tr>
                          <td><%= f.label "Pet Type" %></td>
                          <td> <%= 
                    f.select :pet_type,options_for_select([["Cat", "Cat"], ['Dog',"Dog"]]),{:include_blank=>true}, :id=>"first_select", 
                        :'data-remote' => 'true', # important for UJS
                        :'data-url' => url_for(:controller => 'pets', :action => 'getdata'), # we get the data from here!
                        :'data-type' => 'json' # tell jQuery to parse the response as JSON!
                  %></td>
                        </tr>
                        <tr>
                          <td><%= f.label :Breed %></td>
                          <td> <%= 
                    f.select :breed,"<option>Please select something from first select!</option>",{},:id=>"second_select"
                  %></td>
                        </tr>
                        <tr>
                          <td><%= f.label :body_condition_score %></td>
                          <td> <%= f.select(:body_condition_score,options_for_select([['Slim/Normal',"Normal"],            ['Fat',"Fat"]])) %></td>
                        </tr>
                         <tr>
                          <td><%= f.label "weight in Kg" %></td>
                          <td> <%= f.text_field :body_weight %></td>
                        </tr>
                         </tr>
                         <tr>
                          <td><%= f.label :activity_level %></td>
                          <td> <%= f.select(:activity,options_for_select([['Active',"Active"],            ['Inactive',"Inactive"]])) %></td>
                        </tr>

                      </tbody>
                    </table>
                    
                    <div class="col-md-offset-4"><%= f.submit nil, :class=>"btn btn-danger" %>
                    

                    <a href='http://localhost:3000/pets' class="btn btn-danger">Back</a><%end%></div>
                    
                    
                  

                  
                </div>
              </div>
            </div>
          </div>
        



        <!-- Booking End -->      
<%= render partial: "layouts/foot"%>

petQuest/app/views/pets/show.html.erb
<%=render partial: "layouts/head"%>
<!-- Banner Start -->
      
      <div class="banner padd">
        <div class="container">
          <!-- Image -->
          <img class="img-responsive" src="http://dakotapethospital.com/clients/14546/images/slideshows/29628/banner%204%20edited.jpg" alt="" />
          <!-- Heading -->
          <h2 class="brown">View Pet</h2>
          <ol class="breadcrumb">
            <li><a href="index.html"></a></li>
            <li class="active"></li>
          </ol>
          <div class="clearfix"></div>
        </div>
      </div>
      <br>
      <!-- Banner End -->
<div class="container">
  <div class ="row">
    <div class = "col-md-6"><img class="img-responsive" src="http://www.hdwallpapers11.com/wallpapers/2560x1600/cute-white-dog-2560x1600.jpg"></div>

    <div class="table-responsive col-md-5 col-md-offset-1">
                    <table class="table table-bordered">
                      
                      <tbody>
                        <tr>
                          <td>Name</td>
                          <td> <%= @pet.name %></td>
                        </tr>
                        <tr>
                          <td>Gender</td>
                          <td><%= @pet.gender %></td>
                        </tr>
                        <tr>
                          <td>Age</td>
                          <td><%= @pet.age %>  <%= @plural_year %> <%= @pet.months %> <%= @plural_month %> </td>
                        </tr>
                        <tr>
                          <td>Gender</td>
                          <td><%= @pet.gender %></td>
                        </tr>
                        <tr>
                          <td>Pet Type</td>
                          <td> <%= @pet.pet_type %></td>
                        </tr>
                        <tr>
                          <td>Breed</td>
                          <td> <%= @pet.breed %></td>
                        </tr>
                        <tr>
                          <td>Body Condition Score</td>
                          <td> <%= @pet.body_condition_score %></td>
                        </tr>
                        <tr>
                          <td>Weight </td>
                          <td> <%= @pet.body_weight %> Kg </td>
                        </tr>
                        <tr>
                          <td>Activity Level</td>
                          <td> <%= @pet.activity %></td>
                        </tr>
                        <tr>
                          <td>Recommended Daily Metabolic Energy </td>
                          <td> <%= @me_result %> KCal </td>
                        </tr>
                      </tbody>
                    </table>
                    <div class= "col-md-offset-1"><%= link_to 'Edit', edit_pet_path(@pet), :class=>"btn btn-danger", :type=>"button"%>   
                    <a href="http://localhost:3000/pets/new" class="btn btn-danger">Add a new pet</a>
 
                    <a href="http://localhost:3000/foods" class="btn btn-danger">Select food</a>

                    <a href="http://localhost:3000/pets" class="btn btn-danger" type ="button">View Pets</a></div>
                  </div>
                </div>
              </div>  
 
  

   <br><br><br>
  
  </div></div>
<%=render partial: "layouts/foot"%>